name: fredgibbs
description: Digital History and Humanities Blog 
url: http://fredgibbs.net
permalink: :categories/:title
safe: true
highlighter: pygments
markdown: redcarpet
kramdown: 
  parse_block_html: true